export function TermsOfUseContent() {
  return (
    <div
      className="text-charcoal-mid"
      style={{ fontFamily: "Inter, sans-serif", fontSize: "0.9rem", lineHeight: 1.8 }}
    >
      <p className="text-charcoal-soft mb-6">Effective Date: November 8, 2025 · Last Updated: April 16, 2026</p>
      <p className="mb-4">Welcome to Credenza ("Credenza," "we," "our," or "us"). These Terms of Use ("Terms") govern your access to and use of usecredenza.com and any related services or applications (collectively, the "Platform").</p>
      <p className="mb-4">By accessing or using the Platform, you agree to these Terms. If you do not agree, please do not use Credenza.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>1. Overview</h2>
      <p className="mb-4">Credenza provides identity verification and trade-program management services for the design industry. The Platform is currently in development, and functionality may change without notice.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>2. Eligibility</h2>
      <p className="mb-4">You must be at least 18 years old and capable of entering into a binding contract to use the Platform. By using Credenza, you represent that you meet these requirements.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>3. User Accounts</h2>
      <p className="mb-4">If you create an account, you are responsible for maintaining its confidentiality and for all activities under your account. You agree to provide accurate, complete, and current information when registering for an account and when using any of the services provided therein. Notify us immediately of any unauthorized use.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>4. Acceptable Use</h2>
      <p className="mb-2">You agree not to:</p>
      <ul className="mb-4 pl-5 list-disc">
        <li className="mb-2">Use the Platform for any unlawful purpose or in violation of these Terms.</li>
        <li className="mb-2">Impersonate any person or entity, or falsely claim an affiliation.</li>
        <li className="mb-2">Interfere with or disrupt the Platform's operation or servers.</li>
        <li className="mb-2">Attempt to gain unauthorized access to any part of the Platform.</li>
      </ul>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>5. Intellectual Property</h2>
      <p className="mb-4">All content, trademarks, and data on the Platform—including text, graphics, logos, and software—are owned by Credenza or our licensors. You may not copy, modify, distribute, or create derivative works using any website content without our prior written consent.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>6. User Content</h2>
      <p className="mb-4">By submitting personal or confidential information (e.g., documents, certificates, or profile details) to the Platform, you grant Credenza a non-exclusive, worldwide, royalty-free license to use, store, and display that content solely to provide and improve our services.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>7. Disclaimers</h2>
      <p className="mb-4">The Platform is provided "as is" and "as available." We make no warranties, express or implied, regarding its operation, accuracy, or availability. We do not guarantee that the Platform will be error-free or uninterrupted. The Platform will automatically generate resale certificates based on the information you provide. Credenza does not guarantee the accuracy, validity, or legal compliance of any resale certificates. You are responsible for verifying the accuracy of resale certificates and any other documents generated.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>8. Indemnity</h2>
      <p className="mb-4">You agree to indemnify, defend, and hold harmless Credenza, its affiliates, and their respective officers, directors, employees, and agents from and against any claims, damages, losses, liabilities, costs, or expenses (including reasonable attorneys' fees) arising from (i) your use of the Platform, (ii) your breach of these Terms, (iii) any incorrect or outdated information you provide, or (iv) any penalties, fines, or other damages or liabilities resulting from the resale certificates generated by the Platform.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>9. Limitation of Liability</h2>
      <p className="mb-4">To the fullest extent permitted by law, Credenza and its affiliates, officers, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Platform. Credenza's total liability for any claim arising out of or related to the Platform shall not exceed the amount paid, if any, by you to the Company for access to the Platform. This limitation applies regardless of the form of action, whether in contract, tort, strict liability, or otherwise.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>10. Termination</h2>
      <p className="mb-4">We reserve the right to suspend or terminate your access to the Platform at any time, with or without cause or notice, if we believe you have violated these Terms or engaged in conduct harmful to Credenza or other users.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>11. Governing Law and Disputes</h2>
      <p className="mb-4">These Terms are governed by the laws of the State of Delaware, without regard to conflict-of-law principles. Any disputes shall be resolved in the state or federal courts located in Delaware.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>12. Changes to These Terms</h2>
      <p className="mb-4">We may update these Terms from time to time. Continued use of the Platform after changes are posted constitutes your acceptance of the revised Terms.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>13. Miscellaneous</h2>
      <p className="mb-4">If any provision of these Terms is held invalid or unenforceable, the remaining provisions shall remain in full force and effect. No waiver by Credenza of any breach of these Terms shall constitute a waiver of any other or subsequent breach.</p>

      <h2 className="font-freight mt-8 mb-3 text-charcoal" style={{ fontSize: "1.15rem" }}>14. Contact Information</h2>
      <p>For questions or concerns about these Terms, please contact us at:</p>
      <p className="mt-2">Credenza<br />Email: <a href="mailto:info@usecredenza.com" className="text-teal-mid">info@usecredenza.com</a><br />Website: usecredenza.com</p>
    </div>
  );
}
