/**
 * Static prerender for AEO / answer-engine crawlers.
 *
 * The marketing site is a client-rendered Vite SPA. Each page sets its
 * <head> (title, meta description, canonical, JSON-LD) inside a useEffect,
 * which only runs after JavaScript executes. Raw-HTML crawlers (ClaudeBot,
 * GPTBot, PerplexityBot, etc.) don't run that JS, so without this step they
 * see the homepage's generic <head> and an empty #root for every route.
 *
 * This postbuild step serves the freshly-built dist/, drives headless Chrome
 * through every known route, lets each page's effects run, and snapshots the
 * fully-rendered HTML to dist/<route>/index.html. The SPA bundle is left in
 * the snapshot, so real users still hydrate into the normal interactive app —
 * this is pure progressive enhancement for crawlers and first paint.
 *
 * Safety: prerendering can NEVER block a deploy. If Chrome fails to launch we
 * log and exit 0 (the SPA shell ships, i.e. today's behavior). Per-route
 * failures are logged and skipped, leaving that route to the SPA fallback.
 */
import { createServer } from "node:http";
import { readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { join, extname, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const DIST = join(dirname(fileURLToPath(import.meta.url)), "..", "dist");

const SITE_URL = "https://usecredenza.com";

// Every static route in src/App.tsx except the "*" (NotFound) wildcard.
//
// This table is also the source of the sitemap. It used to be duplicated by
// hand in public/sitemap.xml, which drifted: six of thirteen indexable routes
// were missing, including the three highest-value landing pages. Adding a route
// here now prerenders it AND lists it, so the two can't disagree.
// `index: false` prerenders the route but keeps it out of the sitemap — use it
// for anything that also sets `noindex` via usePageMeta.
const ROUTES = [
  { path: "/", priority: "1.0", changefreq: "weekly" },
  { path: "/for-designers", priority: "0.8", changefreq: "weekly" },
  { path: "/shopify", priority: "0.8", changefreq: "weekly" },
  { path: "/resale-certificate-management", priority: "0.8", changefreq: "weekly" },
  { path: "/automated-designer-verification", priority: "0.8", changefreq: "weekly" },
  { path: "/pricing", priority: "0.9", changefreq: "monthly" },
  { path: "/resources", priority: "0.7", changefreq: "weekly" },
  { path: "/resources/interior-designer-resale-certificate-guide", priority: "0.8", changefreq: "monthly" },
  { path: "/resources/how-to-choose-trade-program-software", priority: "0.8", changefreq: "monthly" },
  { path: "/about", priority: "0.6", changefreq: "monthly" },
  { path: "/privacy-policy", priority: "0.3", changefreq: "monthly" },
  { path: "/terms-of-use", priority: "0.3", changefreq: "monthly" },
  { path: "/vendor-agreement", priority: "0.3", changefreq: "monthly" },
  { path: "/dpa", priority: "0.3", changefreq: "monthly" },
  { path: "/eula", priority: "0.3", changefreq: "monthly" },
  // Internal creative-export surface — prerendered, but noindex and unlisted.
  { path: "/social-cards", index: false },
];

function buildSitemap(routes) {
  const entries = routes
    .filter((r) => r.index !== false)
    .map((r) =>
      [
        "  <url>",
        `    <loc>${SITE_URL}${r.path === "/" ? "/" : r.path}</loc>`,
        `    <changefreq>${r.changefreq}</changefreq>`,
        `    <priority>${r.priority}</priority>`,
        "  </url>",
      ].join("\n"),
    )
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/prerender.mjs from the ROUTES table. Do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries,
    "</urlset>",
    "",
  ].join("\n");
}

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".webmanifest": "application/manifest+json",
};

async function exists(p) {
  try {
    const s = await stat(p);
    return s.isFile();
  } catch {
    return false;
  }
}

// Tiny static server with SPA fallback to index.html — mirrors how Vercel
// serves the built site (static files first, SPA fallback otherwise).
function startServer(shell) {
  const server = createServer(async (req, res) => {
    try {
      const url = new URL(req.url, "http://127.0.0.1");
      const pathname = decodeURIComponent(url.pathname);

      // Every route navigation renders from the pristine build shell held in
      // memory — never from a file on disk. The loop below overwrites
      // dist/index.html with the homepage snapshot on its first iteration; if
      // the SPA fallback re-read that file, each later route would start from
      // the homepage's fully-rendered DOM and inherit the <script
      // type="application/ld+json"> blocks the homepage injected at runtime.
      // That is exactly how the homepage FAQPage ended up on /privacy-policy.
      if (!extname(pathname)) {
        res.writeHead(200, { "Content-Type": MIME[".html"] });
        res.end(shell);
        return;
      }

      const filePath = join(DIST, pathname);
      if (!(await exists(filePath))) {
        res.writeHead(404);
        res.end("not found");
        return;
      }

      const body = await readFile(filePath);
      res.writeHead(200, { "Content-Type": MIME[extname(filePath)] || "application/octet-stream" });
      res.end(body);
    } catch (err) {
      res.writeHead(500);
      res.end(String(err));
    }
  });
  return new Promise((resolve) => {
    server.listen(0, "127.0.0.1", () => resolve({ server, port: server.address().port }));
  });
}

function outPathFor(route) {
  if (route === "/") return join(DIST, "index.html");
  return join(DIST, route.replace(/^\//, ""), "index.html");
}

// Launch headless Chrome. On Vercel/Lambda build containers the bundled
// puppeteer Chrome can't launch (missing system libs), so use the
// @sparticuz/chromium binary + puppeteer-core there. Locally (macOS/dev),
// use the full puppeteer package, which ships its own working Chrome.
async function launchBrowser() {
  const onVercel = !!process.env.VERCEL || !!process.env.AWS_REGION || !!process.env.AWS_LAMBDA_FUNCTION_NAME;
  if (onVercel) {
    const chromium = (await import("@sparticuz/chromium")).default;
    const puppeteer = (await import("puppeteer-core")).default;
    return puppeteer.launch({
      args: [...chromium.args, "--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
      executablePath: await chromium.executablePath(),
      headless: chromium.headless ?? true,
    });
  }
  const puppeteer = (await import("puppeteer")).default;
  return puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"],
  });
}

async function main() {
  // Write the sitemap first: it's pure string building with no Chrome
  // dependency, so it still ships on build hosts where prerendering bails.
  await writeFile(join(DIST, "sitemap.xml"), buildSitemap(ROUTES), "utf8");
  const listed = ROUTES.filter((r) => r.index !== false).length;
  console.log(`[prerender] sitemap.xml — ${listed} of ${ROUTES.length} routes listed`);

  // Capture the shell before the loop starts overwriting dist/index.html.
  const shell = await readFile(join(DIST, "index.html"));

  const { server, port } = await startServer(shell);
  const base = `http://127.0.0.1:${port}`;

  let browser;
  try {
    browser = await launchBrowser();
  } catch (err) {
    console.warn("[prerender] could not launch Chrome, skipping prerender (SPA shell will ship):", err?.message);
    server.close();
    return; // exit 0 — never block a deploy
  }

  let ok = 0;
  let failed = 0;
  for (const { path: route } of ROUTES) {
    const page = await browser.newPage();
    try {
      await page.goto(`${base}${route}`, { waitUntil: "networkidle0", timeout: 30000 });
      // Give per-page useEffect head injection a beat to run, then confirm a
      // non-empty title was set (every page sets one) before snapshotting.
      await page
        .waitForFunction("document.title && document.title.length > 0", { timeout: 5000 })
        .catch(() => {});
      await new Promise((r) => setTimeout(r, 300));

      const html = "<!DOCTYPE html>\n" + (await page.evaluate(() => document.documentElement.outerHTML));
      const out = outPathFor(route);
      await mkdir(dirname(out), { recursive: true });
      await writeFile(out, html, "utf8");
      ok++;
      console.log(`[prerender] ✓ ${route} -> ${out.replace(DIST, "dist")}`);
    } catch (err) {
      failed++;
      console.warn(`[prerender] ✗ ${route} skipped (SPA fallback): ${err?.message}`);
    } finally {
      await page.close().catch(() => {});
    }
  }

  await browser.close().catch(() => {});
  server.close();
  console.log(`[prerender] done — ${ok} prerendered, ${failed} skipped, ${ROUTES.length} total`);
}

main().catch((err) => {
  // Last-resort guard: a crash here must not fail the production build.
  console.warn("[prerender] unexpected error, shipping SPA shell:", err?.message);
  process.exit(0);
});
